### ISSUE TITLE
开始写博客了

### ISSUE THREAD

**Issue by msqtt** [msqtt/blog#2]
今天是 2023-12-03 还有一个月今年就过了，我决定用 issue 写博客了 :sleepy: 

有很多问题还不是很清楚，比如，如何与正常的 issue 区分开呢？
写完的博客应该 close 吗，还是保持 open 就行了 :thinking:

**Comment by therainisme** [comment]
点仓库的设置，点 Discussions，点击开启，那个更像 Blog

**Comment by msqtt** [comment]
> 点仓库的设置，点 Discussions，点击开启，那个更像 Blog

原来如此，受教了板哥 :heart:  :+1:
